export type Response = -2 | -1 | 0 | 1 | 2

// Names of lucide-react icons used to represent each pole of an axis.
// Kept as plain strings here so this data file has no React/UI dependency;
// AxesViz.tsx maps these to actual icon components.
export type IconKey =
  | 'landmark'
  | 'store'
  | 'users'
  | 'briefcase'
  | 'globe'
  | 'flag'
  | 'atom'
  | 'church'
  | 'flame'
  | 'shield'
  | 'sparkles'
  | 'scroll-text'
  | 'heart-handshake'
  | 'swords'
  | 'palette'
  | 'user-check'
  | 'map-pin'
  | 'building-2'
  | 'leaf'
  | 'factory'
  | 'rotate-cw'
  | 'zap'
  | 'home'
  | 'scale'
  | 'trending-up'
  | 'unlock'
  | 'cpu'
  | 'shield-alert'

export interface Question {
  id: string
  text: string
  axes: Partial<Record<string, number>>
}

export interface AxisConfig {
  key: string
  categoryName: string // e.g. "Economy" — the category this axis belongs to
  leftLabel: string
  rightLabel: string
  centerLabel: string // label shown when the score is close to neutral
  leftIcon: IconKey
  rightIcon: IconKey
  leftColor: string
  rightColor: string
}

export interface Party {
  name: string
  abbrev: string
  x: number // economic: -10 left to +10 right
  y: number // authority: -10 libertarian to +10 authoritarian
  color: string
  wing: string
}

export interface Ideology {
  name: string
  abbrev: string
  x: number // economic: -10 left to +10 right
  y: number // authority: -10 libertarian to +10 authoritarian
  color: string
  family: string
  description: string
}

// ─────────────────────────────────────────────
// POLITICAL COMPASS
// econ: negative = left, positive = right
// auth: negative = libertarian, positive = authoritarian
// ─────────────────────────────────────────────
export const politicalCompassQuestions: Question[] = [
  // Economic
  { id: 'pc1', text: 'The free market is the most efficient mechanism for distributing goods and services in society.', axes: { econ: 2 } },
  { id: 'pc2', text: 'Workers deserve a significant share of the profits generated by their labor.', axes: { econ: -2 } },
  { id: 'pc3', text: 'Universal healthcare, funded by taxation, is a right rather than a privilege.', axes: { econ: -2 } },
  { id: 'pc4', text: 'Businesses perform better, and society benefits more, when government regulation is minimized.', axes: { econ: 2 } },
  { id: 'pc5', text: 'Essential utilities like water, electricity, and public transport should be publicly owned.', axes: { econ: -1.5 } },
  { id: 'pc6', text: 'Inheritance taxes are an unjust burden on families who worked hard to build wealth.', axes: { econ: 1.5 } },
  { id: 'pc7', text: 'Reducing the wealth gap between the richest and poorest citizens should be a central goal of government.', axes: { econ: -1.5 } },
  { id: 'pc8', text: 'Strong labor unions are essential for protecting the interests of working people.', axes: { econ: -1.5 } },
  { id: 'pc9', text: 'A national minimum wage harms small businesses and ultimately destroys jobs.', axes: { econ: 1.5 } },
  { id: 'pc10', text: 'Globalization has mainly enriched corporations and the wealthy while harming ordinary workers.', axes: { econ: -1 } },
  // Authority
  { id: 'pc11', text: 'Governments are justified in monitoring private communications to prevent terrorism.', axes: { auth: 2 } },
  { id: 'pc12', text: 'The use of recreational drugs between consenting adults should not be a criminal matter.', axes: { auth: -2 } },
  { id: 'pc13', text: 'Citizens should always obey the law, even when they personally believe it to be unjust.', axes: { auth: 2 } },
  { id: 'pc14', text: 'Abortion should be freely and legally available to anyone who chooses it.', axes: { auth: -2 } },
  { id: 'pc15', text: 'A strong sense of national identity is essential for a healthy and cohesive society.', axes: { auth: 1.5 } },
  { id: 'pc16', text: 'Freedom of expression must be protected even when speech is offensive or hateful.', axes: { auth: -2 } },
  { id: 'pc17', text: 'The death penalty can be a justifiable punishment for the most serious crimes.', axes: { auth: 1.5 } },
  { id: 'pc18', text: 'Religious values and principles should influence the laws and policies of government.', axes: { auth: 2 } },
  { id: 'pc19', text: 'Civil disobedience is sometimes necessary and justified when laws are deeply unjust.', axes: { auth: -1.5 } },
  { id: 'pc20', text: 'Strict discipline and firm moral instruction are among the most important things a society can instill in children.', axes: { auth: 1.5 } },
  // Additional economic questions (finer resolution)
  { id: 'pc21', text: 'Automation and AI-driven job loss will require significant new social safety nets.', axes: { econ: -1 } },
  { id: 'pc22', text: 'People who work harder and take more risks deserve to keep most of what they earn.', axes: { econ: 1 } },
  { id: 'pc23', text: 'Housing should be treated primarily as a human right rather than an investment asset.', axes: { econ: -1.5 } },
  { id: 'pc24', text: 'Free trade and open markets, even when they cost some domestic jobs, benefit the economy overall.', axes: { econ: 1 } },
  { id: 'pc25', text: 'A universal basic income is a reasonable response to growing economic insecurity.', axes: { econ: -1.5 } },
  // Additional authority/social questions (finer resolution)
  { id: 'pc26', text: 'Gender roles are largely a social construct rather than a biological given.', axes: { auth: -1.5 } },
  { id: 'pc27', text: 'A well-armed citizenry is one of the best safeguards against government overreach.', axes: { auth: -1 } },
  { id: 'pc28', text: 'Schools should teach a shared national history that fosters pride and unity.', axes: { auth: 1.5 } },
  { id: 'pc29', text: 'Government surveillance of protest movements is rarely, if ever, justified.', axes: { auth: -1.5 } },
  { id: 'pc30', text: 'Immigration policy should prioritize preserving a country\'s existing cultural character.', axes: { auth: 1.5 } },
]

export const partyPositions: Party[] = [
  { name: 'Democratic Party', abbrev: 'DEM', x: -2.5, y: 1.5, color: '#3B82F6', wing: 'Center-Left' },
  { name: 'Republican Party', abbrev: 'GOP', x: 4.5, y: 5, color: '#EF4444', wing: 'Right' },
  { name: 'Libertarian Party', abbrev: 'LIB', x: 6.5, y: -6, color: '#EAB308', wing: 'Right-Libertarian' },
  { name: 'Green Party', abbrev: 'GRN', x: -5.5, y: -1.5, color: '#22C55E', wing: 'Left-Libertarian' },
  { name: 'Democratic Socialists of America', abbrev: 'DSA', x: -7.5, y: -0.5, color: '#EC4899', wing: 'Far Left' },
  { name: 'Constitution Party', abbrev: 'CST', x: 5.5, y: 7, color: '#F97316', wing: 'Far Right' },
  { name: 'Forward Party', abbrev: 'FWD', x: 0, y: -0.5, color: '#A855F7', wing: 'Centrist' },
  { name: 'American Solidarity Party', abbrev: 'ASP', x: -1.5, y: 2.5, color: '#14B8A6', wing: 'Center (Communitarian)' },
]

// ─────────────────────────────────────────────
// IDEOLOGY DATABASE
// A broader set of political traditions/ideologies (not tied to any
// single country's current parties) used to find the closest
// conceptual match to a user's compass position. Positions are
// approximate placements commonly used for illustrative purposes,
// not precise measurements.
// ─────────────────────────────────────────────
export const ideologyPositions: Ideology[] = [
  { name: 'Anarcho-Communism', abbrev: 'A-COM', x: -9.5, y: -9, color: '#111111', family: 'Far Left', description: 'Seeks to abolish both the state and private property, replacing them with voluntary, stateless communes organized around collective ownership.' },
  { name: 'Anarcho-Syndicalism', abbrev: 'A-SYN', x: -8.5, y: -7.5, color: '#7F1D1D', family: 'Far Left', description: 'Favors organizing the economy through worker-run labor unions and direct action, with the eventual abolition of the state.' },
  { name: 'Libertarian Socialism', abbrev: 'LB-SOC', x: -7.5, y: -6, color: '#B91C1C', family: 'Left', description: 'Combines opposition to concentrated economic power with a strong emphasis on personal and civil freedoms, favoring decentralized worker control.' },
  { name: 'Marxism-Leninism', abbrev: 'M-L', x: -8, y: 8.5, color: '#7F1D1D', family: 'Far Left (Authoritarian)', description: 'A revolutionary current that pairs state ownership of the economy with a centralized single-party state directing the transition to communism.' },
  { name: 'Maoism', abbrev: 'MAO', x: -7, y: 8, color: '#991B1B', family: 'Far Left (Authoritarian)', description: 'A variant of Marxism-Leninism emphasizing peasant-led revolution, continuous class struggle, and strong centralized party control.' },
  { name: 'Democratic Socialism', abbrev: 'D-SOC', x: -6, y: -2, color: '#DB2777', family: 'Left', description: 'Seeks to achieve socialist economic goals — worker ownership, reduced inequality — through democratic institutions rather than revolution.' },
  { name: 'Eco-Socialism', abbrev: 'ECO-S', x: -6.5, y: -2.5, color: '#15803D', family: 'Left', description: 'Merges socialist critiques of capitalism with the view that ecological limits require a fundamental restructuring of the economy.' },
  { name: 'Social Democracy', abbrev: 'S-DEM', x: -4, y: -1, color: '#2563EB', family: 'Center-Left', description: 'Supports a market economy tempered by a strong welfare state, progressive taxation, and robust labor protections.' },
  { name: 'Green Politics', abbrev: 'GRN', x: -4.5, y: -2, color: '#22C55E', family: 'Center-Left', description: 'Centers environmental sustainability, grassroots democracy, and social justice as its core organizing principles.' },
  { name: 'Progressivism', abbrev: 'PROG', x: -3, y: -1.5, color: '#3B82F6', family: 'Center-Left', description: 'Favors active government intervention to expand social and economic equality and to reform existing institutions.' },
  { name: 'Modern / Social Liberalism', abbrev: 'S-LIB', x: -2, y: -1, color: '#60A5FA', family: 'Center', description: 'Supports individual liberty alongside government action to correct market failures and expand opportunity.' },
  { name: 'Georgism', abbrev: 'GEO', x: -2.5, y: -2, color: '#0EA5E9', family: 'Center', description: 'A market-friendly tradition that would replace most taxes with a single tax on the unimproved value of land.' },
  { name: 'Third Way', abbrev: 'T-WAY', x: -1, y: 0, color: '#818CF8', family: 'Center', description: 'A centrist synthesis that blends market economics with targeted social programs, popular in the 1990s–2000s.' },
  { name: 'Centrism', abbrev: 'CENT', x: 0, y: 0, color: '#9CA3AF', family: 'Center', description: 'Avoids strong ideological commitments, favoring pragmatic, moderate positions across the economic and social spectrum.' },
  { name: 'Christian Democracy', abbrev: 'C-DEM', x: 1.5, y: 2, color: '#0D9488', family: 'Center-Right', description: 'Combines a market economy and social conservatism with a strong communitarian and religiously-informed welfare tradition.' },
  { name: 'Classical Liberalism', abbrev: 'C-LIB', x: 3.5, y: -2.5, color: '#FBBF24', family: 'Center-Right', description: 'Prioritizes free markets, limited government, and strong individual civil and economic liberties.' },
  { name: 'Distributism', abbrev: 'DIST', x: -1, y: 2.5, color: '#78350F', family: 'Center', description: 'Favors widely distributed private property (small farms, family businesses) over both large-scale capitalism and state socialism.' },
  { name: 'Conservatism', abbrev: 'CONS', x: 3, y: 3, color: '#B91C1C', family: 'Right', description: 'Emphasizes gradual change, established institutions, tradition, and social order over rapid reform.' },
  { name: 'Neoconservatism', abbrev: 'NEO-C', x: 4, y: 3.5, color: '#DC2626', family: 'Right', description: 'Combines a assertive, interventionist foreign policy with support for free markets and traditional social values.' },
  { name: 'National Conservatism', abbrev: 'N-CON', x: 5, y: 4.5, color: '#EA580C', family: 'Right', description: 'Emphasizes national sovereignty, cultural cohesion, and restricting immigration alongside traditional social values.' },
  { name: 'Paleoconservatism', abbrev: 'PALEO', x: 5.5, y: 4, color: '#C2410C', family: 'Right', description: 'Stresses traditionalism, decentralization, and skepticism of immigration, foreign intervention, and globalization.' },
  { name: 'Right-Libertarianism', abbrev: 'R-LIB', x: 7, y: -6.5, color: '#EAB308', family: 'Right-Libertarian', description: 'Advocates minimal government limited to protecting property rights and enforcing contracts, with maximum market freedom.' },
  { name: 'Anarcho-Capitalism', abbrev: 'A-CAP', x: 9.5, y: -9, color: '#CA8A04', family: 'Far Right-Libertarian', description: 'Would replace the state entirely with private markets and voluntary contracts, including for law and security.' },
  { name: 'Fascism', abbrev: 'FASC', x: 6.5, y: 9, color: '#1F2937', family: 'Far Right (Authoritarian)', description: 'A historical authoritarian ultranationalist movement subordinating the individual to the state and prioritizing national unity by force.' },
  { name: 'Theocracy', abbrev: 'THEO', x: 2, y: 8.5, color: '#4C1D95', family: 'Far Right (Authoritarian)', description: 'Places religious law and clerical authority at the center of governance, with limited separation between church and state.' },
]

// ─────────────────────────────────────────────
// VOTE COMPASS
// Same 2 axes, questions framed around specific policy issues
// Results show party proximity
// ─────────────────────────────────────────────
export const voteCompassQuestions: Question[] = [
  { id: 'vc1', text: 'The United States should implement a universal single-payer healthcare system.', axes: { econ: -2, auth: -0.5 } },
  { id: 'vc2', text: 'The federal minimum wage should be raised significantly to reflect the cost of living.', axes: { econ: -1.5 } },
  { id: 'vc3', text: 'Capital gains should be taxed at the same rate as ordinary income.', axes: { econ: -1.5 } },
  { id: 'vc4', text: 'The United States should reduce military spending and invest more in domestic programs.', axes: { econ: -1, auth: -1 } },
  { id: 'vc5', text: 'Immigration levels should be significantly reduced to protect American jobs and culture.', axes: { econ: 0.5, auth: 1.5 } },
  { id: 'vc6', text: 'The federal government should pass major new legislation to address climate change.', axes: { econ: -1, auth: 0.5 } },
  { id: 'vc7', text: 'Citizens should have a largely unrestricted right to own and carry firearms.', axes: { econ: 0.5, auth: -1.5 } },
  { id: 'vc8', text: 'Abortion should be legal and accessible at the federal level.', axes: { auth: -2 } },
  { id: 'vc9', text: 'Marijuana should be legalized at the federal level.', axes: { auth: -1.5 } },
  { id: 'vc10', text: 'Corporate tax rates should be substantially increased.', axes: { econ: -2 } },
  { id: 'vc11', text: 'The government should significantly expand social security and retirement benefits.', axes: { econ: -1.5 } },
  { id: 'vc12', text: 'The United States should take a harder stance against China in trade and foreign policy.', axes: { econ: 0.5, auth: 1.5 } },
  { id: 'vc13', text: 'Free trade agreements generally benefit the American economy and should be expanded.', axes: { econ: 1.5 } },
  { id: 'vc14', text: 'The government should reduce the national debt even if it means cutting services.', axes: { econ: 1.5 } },
  { id: 'vc15', text: 'Mass surveillance programs are necessary and justified for national security.', axes: { auth: 2 } },
  { id: 'vc16', text: 'The wealthy should be taxed significantly more to fund public services and reduce inequality.', axes: { econ: -2 } },
  { id: 'vc17', text: 'Government regulation of the internet and social media platforms should be increased.', axes: { auth: 1.5 } },
  { id: 'vc18', text: 'Private school vouchers should be funded by the government to expand educational choice.', axes: { econ: 1.5, auth: 0.5 } },
  { id: 'vc19', text: 'The United States should pursue a more isolationist foreign policy.', axes: { econ: 0, auth: 0.5 } },
  { id: 'vc20', text: 'Police funding should be maintained or increased to combat rising crime.', axes: { auth: 2 } },
]

// ─────────────────────────────────────────────
// 12 AXES
// 2 questions per axis, 24 total
// Positive score = right/second pole
// ─────────────────────────────────────────────
export const twelveAxesQuestions: Question[] = [
  // 1. State vs Market
  { id: 'ta1', text: 'The government should nationalize key industries like banking, energy, and healthcare.', axes: { stateMkt: -2 } },
  { id: 'ta2', text: 'Market competition drives better outcomes than government management of the economy.', axes: { stateMkt: 2 } },
  // 2. Communist vs Capitalist
  { id: 'ta3', text: 'The means of production — factories, resources, firms — should be owned collectively by workers.', axes: { commCap: -2 } },
  { id: 'ta4', text: 'Private ownership of property and businesses is a fundamental and inalienable right.', axes: { commCap: 2 } },
  // 3. Globalist vs Nationalist
  { id: 'ta5', text: 'International institutions like the UN and WTO should have significant authority to resolve global problems.', axes: { globNat: -2 } },
  { id: 'ta6', text: 'A country\'s own national interest must always come first in matters of foreign policy and trade.', axes: { globNat: 2 } },
  // 4. Secular vs Religious
  { id: 'ta7', text: 'Religion should have no role whatsoever in the laws or governance of a modern state.', axes: { secRel: -2 } },
  { id: 'ta8', text: 'The moral framework of religion is essential to a healthy and ordered society.', axes: { secRel: 2 } },
  // 5. Anarchist vs Authoritarian
  { id: 'ta9', text: 'All forms of state authority are ultimately coercive and should be dismantled over time.', axes: { anarAuth: -2 } },
  { id: 'ta10', text: 'A strong central authority is necessary to maintain order, safety, and national coherence.', axes: { anarAuth: 2 } },
  // 6. Progressive vs Conservative
  { id: 'ta11', text: 'Society should actively reform traditional institutions and norms that no longer serve modern needs.', axes: { progCons: -2 } },
  { id: 'ta12', text: 'Traditional values and social structures have stood the test of time and should be preserved.', axes: { progCons: 2 } },
  // 7. Pacifist vs Militarist
  { id: 'ta13', text: 'Military force is almost never a justified solution to international disputes.', axes: { pacMil: -2 } },
  { id: 'ta14', text: 'Military strength and willingness to use force are essential to protecting national interests.', axes: { pacMil: 2 } },
  // 8. Multiculturalist vs Assimilationist
  { id: 'ta15', text: 'A nation is enriched by the diversity of cultures, languages, and traditions within it.', axes: { multiAssim: -2 } },
  { id: 'ta16', text: 'Immigrants should adopt the language, customs, and values of their new country.', axes: { multiAssim: 2 } },
  // 9. Decentralist vs Centralist
  { id: 'ta17', text: 'Power should be devolved to local and regional governments as much as possible.', axes: { decentCent: -2 } },
  { id: 'ta18', text: 'Strong central government is needed to ensure national standards, fairness, and coordination.', axes: { decentCent: 2 } },
  // 10. Environmentalist vs Industrialist
  { id: 'ta19', text: 'Protecting the natural environment must take priority over economic growth and development.', axes: { envInd: -2 } },
  { id: 'ta20', text: 'Economic development and industrial progress should not be constrained by environmental concerns.', axes: { envInd: 2 } },
  // 11. Reformist vs Revolutionary
  { id: 'ta21', text: 'Radical, fundamental change in the structure of society is necessary and urgently needed.', axes: { refRev: -2 } },
  { id: 'ta22', text: 'Change should happen slowly and through established legal and democratic processes.', axes: { refRev: 2 } },
  // 12. Internationalist vs Isolationist
  { id: 'ta23', text: 'Nations have a responsibility to intervene in other countries to protect human rights and democracy.', axes: { intlIsol: -2 } },
  { id: 'ta24', text: 'Countries should focus on their own citizens and avoid military or political entanglements abroad.', axes: { intlIsol: 2 } },
]

export const twelveAxesConfig: AxisConfig[] = [
  { key: 'stateMkt', categoryName: 'Economy', leftLabel: 'State', rightLabel: 'Market', centerLabel: 'Mixed Economy', leftIcon: 'landmark', rightIcon: 'store', leftColor: '#EF4444', rightColor: '#3B82F6' },
  { key: 'commCap', categoryName: 'Ownership', leftLabel: 'Communist', rightLabel: 'Capitalist', centerLabel: 'Cooperative', leftIcon: 'users', rightIcon: 'briefcase', leftColor: '#DC2626', rightColor: '#2563EB' },
  { key: 'globNat', categoryName: 'Foreign Outlook', leftLabel: 'Globalist', rightLabel: 'Nationalist', centerLabel: 'Balanced', leftIcon: 'globe', rightIcon: 'flag', leftColor: '#8B5CF6', rightColor: '#D97706' },
  { key: 'secRel', categoryName: 'Religion', leftLabel: 'Secular', rightLabel: 'Religious', centerLabel: 'Agnostic', leftIcon: 'atom', rightIcon: 'church', leftColor: '#6366F1', rightColor: '#F59E0B' },
  { key: 'anarAuth', categoryName: 'Power', leftLabel: 'Anarchist', rightLabel: 'Authoritarian', centerLabel: 'Limited Government', leftIcon: 'flame', rightIcon: 'shield', leftColor: '#10B981', rightColor: '#7C3AED' },
  { key: 'progCons', categoryName: 'Culture', leftLabel: 'Progressive', rightLabel: 'Conservative', centerLabel: 'Moderate', leftIcon: 'sparkles', rightIcon: 'scroll-text', leftColor: '#06B6D4', rightColor: '#B45309' },
  { key: 'pacMil', categoryName: 'Diplomacy', leftLabel: 'Pacifist', rightLabel: 'Militarist', centerLabel: 'Pragmatic', leftIcon: 'heart-handshake', rightIcon: 'swords', leftColor: '#84CC16', rightColor: '#DC2626' },
  { key: 'multiAssim', categoryName: 'Immigration', leftLabel: 'Multiculturalist', rightLabel: 'Assimilationist', centerLabel: 'Middle Ground', leftIcon: 'palette', rightIcon: 'user-check', leftColor: '#F472B6', rightColor: '#78716C' },
  { key: 'decentCent', categoryName: 'Governance', leftLabel: 'Decentralist', rightLabel: 'Centralist', centerLabel: 'Federalist', leftIcon: 'map-pin', rightIcon: 'building-2', leftColor: '#FB923C', rightColor: '#4B5563' },
  { key: 'envInd', categoryName: 'Environment', leftLabel: 'Environmentalist', rightLabel: 'Industrialist', centerLabel: 'Balanced', leftIcon: 'leaf', rightIcon: 'factory', leftColor: '#22C55E', rightColor: '#92400E' },
  { key: 'refRev', categoryName: 'Change', leftLabel: 'Revolutionary', rightLabel: 'Reformist', centerLabel: 'Gradualist', leftIcon: 'zap', rightIcon: 'rotate-cw', leftColor: '#EF4444', rightColor: '#6B7280' },
  { key: 'intlIsol', categoryName: 'Intervention', leftLabel: 'Internationalist', rightLabel: 'Isolationist', centerLabel: 'Selective', leftIcon: 'globe', rightIcon: 'home', leftColor: '#3B82F6', rightColor: '#B91C1C' },
]

// ─────────────────────────────────────────────
// NEOVALUES (5-axis modern values model)
// 4 questions per axis = 20 questions
// ─────────────────────────────────────────────
export const neoValuesQuestions: Question[] = [
  // Axis 1: Economic (Equality ↔ Markets)
  { id: 'nv1', text: 'Extreme wealth inequality is a fundamental threat to a democratic society.', axes: { economic: -2 } },
  { id: 'nv2', text: 'Lower taxes and fewer regulations are the best way to create prosperity for all.', axes: { economic: 2 } },
  { id: 'nv3', text: 'The government should guarantee a minimum standard of living for all citizens.', axes: { economic: -1.5 } },
  { id: 'nv4', text: 'Entrepreneurs and investors are the true engines of social progress.', axes: { economic: 1.5 } },
  // Axis 2: Civil (Liberty ↔ Authority)
  { id: 'nv5', text: 'Individuals should be free to make their own choices without government interference.', axes: { civil: -2 } },
  { id: 'nv6', text: 'Social order requires clear rules and a willingness to enforce them firmly.', axes: { civil: 2 } },
  { id: 'nv7', text: 'The war on drugs has done more harm than good and should be ended.', axes: { civil: -1.5 } },
  { id: 'nv8', text: 'Some limitations on free speech are necessary to protect social cohesion.', axes: { civil: 1.5 } },
  // Axis 3: Diplomatic (Peace/World ↔ Nation/Military)
  { id: 'nv9', text: 'International cooperation is more effective than military power at securing peace.', axes: { diplomatic: -2 } },
  { id: 'nv10', text: 'A country that is unwilling to use military force will ultimately be exploited by its rivals.', axes: { diplomatic: 2 } },
  { id: 'nv11', text: 'Spending on foreign aid and international development benefits everyone in the long run.', axes: { diplomatic: -1.5 } },
  { id: 'nv12', text: 'A country should prioritize the interests of its own citizens above global considerations.', axes: { diplomatic: 1.5 } },
  // Axis 4: Environment (Green ↔ Industrial)
  { id: 'nv13', text: 'Climate change is an existential threat requiring immediate and dramatic government action.', axes: { environment: -2 } },
  { id: 'nv14', text: 'Environmental regulations often do more economic harm than good.', axes: { environment: 2 } },
  { id: 'nv15', text: 'Fossil fuel production should be phased out as quickly as possible.', axes: { environment: -1.5 } },
  { id: 'nv16', text: 'Nuclear energy is a pragmatic and necessary part of the clean energy transition.', axes: { environment: 1 } },
  // Axis 5: Technology (Skeptic ↔ Optimist)
  { id: 'nv17', text: 'Advances in AI and automation will ultimately eliminate more jobs than they create.', axes: { technology: -2 } },
  { id: 'nv18', text: 'Technological progress consistently improves quality of life and should be embraced.', axes: { technology: 2 } },
  { id: 'nv19', text: 'Big tech companies have too much power over society and should be broken up.', axes: { technology: -1.5 } },
  { id: 'nv20', text: 'Genetic engineering and human enhancement technologies will be a net benefit to humanity.', axes: { technology: 1.5 } },
]

export const neoValuesConfig: AxisConfig[] = [
  { key: 'economic', categoryName: 'Economy', leftLabel: 'Equality', rightLabel: 'Markets', centerLabel: 'Mixed', leftIcon: 'scale', rightIcon: 'trending-up', leftColor: '#EF4444', rightColor: '#3B82F6' },
  { key: 'civil', categoryName: 'Civil Liberties', leftLabel: 'Liberty', rightLabel: 'Authority', centerLabel: 'Balanced', leftIcon: 'unlock', rightIcon: 'shield', leftColor: '#22C55E', rightColor: '#7C3AED' },
  { key: 'diplomatic', categoryName: 'Diplomacy', leftLabel: 'Pacifist / World', rightLabel: 'Hawk / Nation', centerLabel: 'Pragmatic', leftIcon: 'heart-handshake', rightIcon: 'swords', leftColor: '#3B82F6', rightColor: '#DC2626' },
  { key: 'environment', categoryName: 'Environment', leftLabel: 'Environmentalist', rightLabel: 'Industrialist', centerLabel: 'Balanced', leftIcon: 'leaf', rightIcon: 'factory', leftColor: '#22C55E', rightColor: '#92400E' },
  { key: 'technology', categoryName: 'Technology', leftLabel: 'Skeptic', rightLabel: 'Techno-Optimist', centerLabel: 'Cautious', leftIcon: 'shield-alert', rightIcon: 'cpu', leftColor: '#F59E0B', rightColor: '#6366F1' },
]

// ─────────────────────────────────────────────
// NEOVALUES ARCHETYPES
// A set of specific, sometimes idiosyncratic political identities
// defined as target positions across the 5 NeoValues axes. Used to
// find a "closest matching" identity for a fun, more specific result
// than the broad axis bars alone provide.
// ─────────────────────────────────────────────
export type ArchetypeIconKey =
  | 'coins' | 'users' | 'crown' | 'triangle' | 'shopping-bag' | 'circle-split'
  | 'cross-shield' | 'sprout' | 'land-plot' | 'rocket' | 'shield-alert'
  | 'tree-pine' | 'building-2' | 'cpu' | 'umbrella' | 'hand-coins' | 'trees'
  | 'dna' | 'mountain' | 'trending-up'

export interface NeoValuesArchetype {
  name: string
  abbrev: string
  color: string
  icon: ArchetypeIconKey
  description: string
  vector: { economic: number; civil: number; diplomatic: number; environment: number; technology: number }
}

export const neoValuesArchetypes: NeoValuesArchetype[] = [
  { name: 'Anarcho-Capitalism', abbrev: 'AC', color: '#EAB308', icon: 'coins', vector: { economic: 9, civil: -9, diplomatic: 2, environment: 2, technology: 6 }, description: 'Markets without a state: property rights and voluntary exchange replace all government function, including law and defense.' },
  { name: 'Anarcho-Communism', abbrev: 'AK', color: '#DC2626', icon: 'users', vector: { economic: -9, civil: -9, diplomatic: -3, environment: 3, technology: -1 }, description: 'Stateless and classless — resources are held in common and coordinated through voluntary federations rather than markets or hierarchy.' },
  { name: 'Anarcho-Monarchism', abbrev: 'AM', color: '#9CA3AF', icon: 'crown', vector: { economic: 2, civil: -6, diplomatic: 1, environment: -1, technology: -2 }, description: 'An unusual pairing: hostility to bureaucratic government alongside sympathy for a symbolic hereditary crown as a unifying, non-political figurehead.' },
  { name: 'Voluntaryism', abbrev: 'VOL', color: '#F59E0B', icon: 'triangle', vector: { economic: 6, civil: -8, diplomatic: -1, environment: 0, technology: 3 }, description: 'All social organization, including law and charity, should arise from consent alone — never from coercive taxation or conscription.' },
  { name: 'Counter-Economics', abbrev: 'CE', color: '#78716C', icon: 'shopping-bag', vector: { economic: 7, civil: -7, diplomatic: -2, environment: -1, technology: 2 }, description: 'Builds alternative, informal markets deliberately outside state regulation and taxation as a form of peaceful resistance.' },
  { name: 'Egoism', abbrev: 'EGO', color: '#14B8A6', icon: 'circle-split', vector: { economic: 3, civil: -9, diplomatic: 0, environment: -3, technology: 3 }, description: "Rejects any authority — moral, religious, or political — that isn't grounded in one's own self-interest and consent." },
  { name: 'Armed Neutrality', abbrev: 'AN', color: '#EF4444', icon: 'cross-shield', vector: { economic: 0, civil: -3, diplomatic: -7, environment: 0, technology: -1 }, description: 'Avoids foreign alliances and interventions entirely, while maintaining a strong, well-armed citizenry for self-defense.' },
  { name: 'Distributism', abbrev: 'DIS', color: '#78350F', icon: 'sprout', vector: { economic: -1, civil: 2, diplomatic: -1, environment: 1, technology: -2 }, description: 'Favors widely distributed small-scale ownership — family farms and businesses — over both corporate capitalism and state socialism.' },
  { name: 'Georgism', abbrev: 'GEO', color: '#0EA5E9', icon: 'land-plot', vector: { economic: -2, civil: -2, diplomatic: -1, environment: 2, technology: 1 }, description: 'A single tax on land value replaces most other taxation, rewarding productive work while capturing unearned land rents.' },
  { name: 'Techno-Progressivism', abbrev: 'TP', color: '#6366F1', icon: 'rocket', vector: { economic: -4, civil: -3, diplomatic: -3, environment: -2, technology: 8 }, description: 'Believes technological acceleration — from biotech to AI — is the most promising path toward a freer, more equal future.' },
  { name: 'Bioconservatism', abbrev: 'BC', color: '#92400E', icon: 'shield-alert', vector: { economic: 1, civil: 3, diplomatic: 1, environment: 2, technology: -7 }, description: 'Wary of biotechnology and AI outpacing our ethical and social capacity to handle them responsibly.' },
  { name: 'Eco-Anarchism', abbrev: 'EA', color: '#16A34A', icon: 'tree-pine', vector: { economic: -6, civil: -7, diplomatic: -4, environment: 8, technology: 2 }, description: 'Imagines small, self-sufficient, ecologically-integrated communities built without centralized state or corporate control.' },
  { name: 'Corporatism', abbrev: 'COR', color: '#B45309', icon: 'building-2', vector: { economic: -2, civil: 5, diplomatic: 2, environment: 0, technology: -1 }, description: 'Organizes the economy around negotiated cooperation between government, worker, and employer associations rather than free markets or central planning.' },
  { name: 'Technocracy', abbrev: 'TEC', color: '#0891B2', icon: 'cpu', vector: { economic: -3, civil: 4, diplomatic: -1, environment: 3, technology: 9 }, description: 'Argues complex policy decisions should be made by scientists, engineers, and subject-matter experts rather than elected politicians.' },
  { name: 'Paternalistic Conservatism', abbrev: 'PC', color: '#A16207', icon: 'umbrella', vector: { economic: -1, civil: 5, diplomatic: 2, environment: -1, technology: -3 }, description: 'Combines support for social hierarchy and tradition with a sense of obligation from the privileged toward the less fortunate.' },
  { name: 'Market Socialism', abbrev: 'MS', color: '#DB2777', icon: 'hand-coins', vector: { economic: -5, civil: -2, diplomatic: -2, environment: 1, technology: 2 }, description: 'Keeps competitive markets for goods and services, but has worker cooperatives — not private shareholders — own the firms.' },
  { name: 'Deep Ecology', abbrev: 'DE', color: '#15803D', icon: 'trees', vector: { economic: -3, civil: -5, diplomatic: -3, environment: 9, technology: -5 }, description: 'Holds that all living things have worth independent of their usefulness to humans, and that industrial society must shrink dramatically.' },
  { name: 'Transhumanism', abbrev: 'TH', color: '#7C3AED', icon: 'dna', vector: { economic: 2, civil: -6, diplomatic: -1, environment: -3, technology: 9 }, description: 'Advocates using technology — genetic engineering, cybernetics, life extension — to fundamentally enhance the human condition.' },
  { name: 'Paleolibertarianism', abbrev: 'PL', color: '#CA8A04', icon: 'mountain', vector: { economic: 5, civil: -5, diplomatic: -5, environment: -2, technology: -1 }, description: 'Pairs a strong commitment to free markets and small government with cultural traditionalism and a non-interventionist foreign policy.' },
  { name: 'Neoliberalism', abbrev: 'NL', color: '#2563EB', icon: 'trending-up', vector: { economic: 5, civil: 1, diplomatic: 3, environment: -2, technology: 4 }, description: 'Emphasizes deregulation, free trade, and privatization, often paired with a fairly interventionist, internationalist foreign policy.' },
]

const NEOVALUES_AXIS_KEYS = ['economic', 'civil', 'diplomatic', 'environment', 'technology'] as const

export function matchArchetypes(scores: Record<string, number>, archetypes: NeoValuesArchetype[]) {
  const ranked = archetypes
    .map((a) => {
      const diffs = NEOVALUES_AXIS_KEYS.map((k) => Math.abs((scores[k] ?? 0) - a.vector[k]))
      const avgDiff = diffs.reduce((s, d) => s + d, 0) / diffs.length
      // Axis range is 20 wide (-10 to +10); express similarity as a percentage.
      const similarity = Math.max(0, Math.round((1 - avgDiff / 20) * 100))
      return { ...a, avgDiff, similarity }
    })
    .sort((a, b) => a.avgDiff - b.avgDiff)

  const best = ranked[0]
  const isExactMatch = best.avgDiff <= 2 // within ~2 points/axis on average = a confident match

  return { ranked, best, isExactMatch }
}

// ─────────────────────────────────────────────
// SCORING
// ─────────────────────────────────────────────
export function scoreAxes(
  questions: Question[],
  answers: Record<string, Response>
): Record<string, number> {
  const totals: Record<string, number> = {}
  const maxes: Record<string, number> = {}

  for (const q of questions) {
    const answer = answers[q.id] ?? 0
    for (const [axis, weight] of Object.entries(q.axes)) {
      totals[axis] = (totals[axis] ?? 0) + answer * (weight ?? 0)
      maxes[axis] = (maxes[axis] ?? 0) + Math.abs(weight ?? 0) * 2
    }
  }

  // Normalize to -10 to +10
  const result: Record<string, number> = {}
  for (const axis of Object.keys(totals)) {
    const max = maxes[axis] ?? 1
    result[axis] = Math.round((totals[axis] / max) * 10 * 10) / 10
  }
  return result
}

export function partyProximity<T extends { x: number; y: number }>(
  userX: number,
  userY: number,
  parties: T[]
) {
  return parties
    .map((p) => ({
      ...p,
      distance: Math.sqrt((p.x - userX) ** 2 + (p.y - userY) ** 2),
    }))
    .sort((a, b) => a.distance - b.distance)
    .map((p) => ({
      ...p,
      alignment: Math.round(Math.max(0, 1 - p.distance / 20) * 100),
    }))
}

export const TESTS = [
  {
    id: 'political-compass',
    name: 'Political Compass',
    abbrev: 'PC',
    tag: 'FOUNDATIONAL',
    questions: 30,
    duration: '~14 min',
    description: 'The classic two-axis model, now with finer-grained questions for sharper resolution. Plots your economic position (left to right) against your stance on authority (libertarian to authoritarian), then matches you to the closest of 25+ political ideologies.',
    resultType: 'compass' as const,
  },
  {
    id: 'vote-compass',
    name: 'Vote Compass',
    abbrev: 'VC',
    tag: 'PARTY ALIGNMENT',
    questions: 20,
    duration: '~8 min',
    description: 'Policy-driven questions calibrated to 8 US political parties, from the majors to Libertarian, Green, DSA, and beyond. Shows where you fall on the ideological map and which parties you align with most closely.',
    resultType: 'vote-compass' as const,
  },
  {
    id: '12axes',
    name: '12 Axes',
    abbrev: '12A',
    tag: 'COMPREHENSIVE',
    questions: 24,
    duration: '~18 min',
    description: 'The most thorough ideology test available. Twelve distinct spectrums — from economic systems to environmental policy to military stance — map the full complexity of your political worldview.',
    resultType: 'axes' as const,
  },
  {
    id: 'neovalues',
    name: 'NeoValues',
    abbrev: 'NV',
    tag: 'MODERN',
    questions: 20,
    duration: '~12 min',
    description: 'A five-axis model built for contemporary politics. Covers economic philosophy, civil liberties, diplomacy, environmental stance, and attitudes toward technology and progress.',
    resultType: 'axes' as const,
  },
]
