import type { Pattern } from './philosorterPhilosophies'
import type { Question } from './data'

export interface Country {
  name: string
  era: string
  govType: string
  x: number // economic: -10 left/collectivist to +10 right/market
  y: number // authority: -10 libertarian to +10 authoritarian
  colors: [string, string, string]
  pattern: Pattern
  description: string
  /** Real national flag emoji (Unicode), for states that still exist today
   * or whose modern successor state uses essentially the same flag. Left
   * undefined for empires/kingdoms with no accurate modern equivalent —
   * those fall back to the drawn emblem instead. */
  flag?: string
}

export interface Politician {
  name: string
  title: string
  era: string
  x: number
  y: number
  colors: [string, string, string]
  pattern: Pattern
  description: string
  /** Real flag emoji of the modern nation-state most associated with this
   * figure, shown as a loose nationality indicator — not a claim that the
   * flag itself existed in their lifetime. */
  flag?: string
}

// ─────────────────────────────────────────────
// COUNTRIES
// Historical and modern states and political systems, positioned on the
// same economic/authority axes used elsewhere on this site. Descriptions
// are brief, factual summaries, not endorsements.
// ─────────────────────────────────────────────
export const countries: Country[] = [
  { name: 'Athenian Democracy', era: 'c. 508–322 BC', govType: 'Direct democracy', x: -3, y: -4, colors: ['#f2e7cf', '#2a4f8f', '#c9a227'], pattern: 'eye', description: 'Citizens voted directly on law and policy in the Assembly, with public offices often filled by lottery. Participation was central; slavery and the exclusion of women and foreigners were its defining limits.' },
  { name: 'Republican Rome', era: '509–27 BC', govType: 'Senatorial-expansionist republic', x: 2, y: 1, colors: ['#7a1f2b', '#e8c96a', '#1c1c1c'], pattern: 'bars', description: 'An aristocratic republic balancing consuls, Senate, and tribunes of the plebs in a mixed system of elective magistracies, expanding across the Mediterranean through citizen legions and a strong cult of civic virtue.' },
  { name: 'Spartan Militarism', era: 'c. 650–192 BC', govType: 'Militarized oligarchy', x: -4, y: 8, colors: ['#3a0f0f', '#c9a227', '#1c1c1c'], pattern: 'triangle', description: 'A rigid, collectivist society built entirely around military training and discipline, with land and labor organized to free citizen-soldiers for constant readiness.' },
  { name: 'Han Dynasty China', era: '206 BC – 220 AD', govType: 'Confucian bureaucratic empire', x: -1, y: 6, colors: ['#8c1c13', '#e8d9b5', '#c9a227'], pattern: 'quarter', description: 'Governed through an examination-based civil bureaucracy steeped in Confucian ethics, blending centralized imperial authority with state-managed grain reserves and infrastructure.' },
  { name: 'Achaemenid Persia', era: 'c. 550–330 BC', govType: 'Multi-ethnic imperial monarchy', x: 1, y: 4, colors: ['#5a2a7a', '#c9a227', '#e8dcc0'], pattern: 'orb', description: 'A vast empire that governed diverse subject peoples through satraps, while notably tolerating local religions, laws, and customs rather than imposing uniformity.' },
  { name: 'Mongol Empire', era: '1206–1368', govType: 'Meritocratic nomadic empire', x: 1, y: 5, colors: ['#122a4a', '#e8dcc0', '#c9a227'], pattern: 'spiral', description: 'Rapidly conquered the largest contiguous land empire in history, promoting officials on merit and safeguarding trade along the Silk Road, while ruling through overwhelming military force.' },
  { name: 'Byzantine Empire', era: '330–1453', govType: 'Orthodox theocratic monarchy', x: 1, y: 8, colors: ['#3a1030', '#c9a227', '#e8dcc0'], pattern: 'cross', description: 'A centralized Christian empire fusing Roman law, Greek culture, and imperial authority understood as divinely sanctioned, governed through an elaborate court bureaucracy.' },
  { name: 'Abbasid Caliphate', era: '750–1258', govType: 'Scholarly theocratic empire', x: -1, y: 6, colors: ['#123c2f', '#c9a227', '#e8dcc0'], pattern: 'orb', description: 'Presided over a golden age of science, philosophy, and trade centered on Baghdad, governing a vast multi-ethnic empire under Islamic law and a centralized caliphate.' },
  { name: 'Mali Empire', era: 'c. 1235–1600', govType: 'Wealthy trading monarchy', x: 2, y: 4, colors: ['#c9a227', '#1c1c1c', '#2f6b3c'], pattern: 'quarter', description: 'Grew immensely wealthy from trans-Saharan gold and salt trade under a centralized monarchy, becoming a center of Islamic scholarship at Timbuktu.' },
  { name: 'Inca Empire', era: '1438–1533', govType: 'Centrally planned empire', x: -7, y: 8, colors: ['#c9a227', '#7a1f2b', '#1c1c1c'], pattern: 'spiral', description: 'Administered an enormous Andean territory through a state-planned economy of labor tribute, redistributed goods, and an extensive road network, with little room for private commerce.' },
  { name: 'Venetian Republic', era: '697–1797', govType: 'Merchant oligarchic republic', x: 6, y: 3, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'A maritime trading power ruled by a merchant aristocracy through elected councils and a doge, prioritizing commercial interests and naval power over territorial conquest.' },
  { name: 'Hanseatic League', era: 'c. 1358–1669', govType: 'Trade confederation', x: 7, y: -5, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'bars', description: 'A loose confederation of merchant guilds and market towns across Northern Europe, cooperating on trade privileges and defense without any central sovereign.' },
  { name: 'Dutch Republic', flag: '🇳🇱', era: '1581–1795', govType: 'Merchant republic', x: 6, y: -4, colors: ['#d97706', '#122a4a', '#e8dcc0'], pattern: 'bars', description: 'A decentralized federation of trading provinces with unusual religious tolerance for its time, whose joint-stock companies pioneered early global capitalism.' },
  { name: 'Elizabethan England', flag: '🇬🇧', era: '1558–1603', govType: 'Mercantilist monarchy', x: 3, y: 5, colors: ['#7a1f2b', '#c9a227', '#122a4a'], pattern: 'cross', description: 'A monarchy balancing royal prerogative against a growing Parliament, expanding overseas trade and naval power while navigating religious upheaval at home.' },
  { name: 'Revolutionary France', flag: '🇫🇷', era: '1789–1799', govType: 'Radical republic', x: -4, y: 2, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'triangle', description: 'Abolished feudal privilege and monarchy in the name of equality and popular sovereignty, before radical factions turned the new republic\u2019s own machinery toward the Terror.' },
  { name: 'Napoleonic France', flag: '🇫🇷', era: '1804–1814', govType: 'Centralized imperial state', x: 1, y: 6, colors: ['#122a4a', '#c9a227', '#7a1f2b'], pattern: 'eye', description: 'Consolidated revolutionary gains into a codified legal system and a highly centralized administration, expanding across Europe under an emperor who governed by personal authority.' },
  { name: 'Victorian Britain', flag: '🇬🇧', era: '1837–1901', govType: 'Constitutional monarchy', x: 5, y: 2, colors: ['#7a1f2b', '#c9a227', '#122a4a'], pattern: 'bars', description: 'An industrializing constitutional monarchy with an expanding franchise, laissez-faire economic orthodoxy at home, and a vast overseas empire.' },
  { name: 'Meiji Japan', flag: '🇯🇵', era: '1868–1912', govType: 'Modernizing constitutional monarchy', x: 2, y: 4, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'orb', description: 'Rapidly industrialized and Westernized its institutions under imperial authority, building a modern army, bureaucracy, and economy within a single generation.' },
  { name: 'Weimar Republic', flag: '🇩🇪', era: '1919–1933', govType: 'Parliamentary democracy', x: -2, y: -2, colors: ['#1c1c1c', '#7a1f2b', '#c9a227'], pattern: 'quarter', description: 'Germany\u2019s first parliamentary democracy, notable for progressive social welfare and a flourishing culture, but destabilized by hyperinflation, political violence, and a fragmented legislature.' },
  { name: 'Soviet Union (early)', era: '1922–1953', govType: 'Single-party planned state', x: -9, y: 8, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'Replaced private industry and land ownership with central state planning under a single party, industrializing rapidly while concentrating political power tightly around the ruling apparatus.' },
  { name: 'New Deal United States', flag: '🇺🇸', era: '1933–1945', govType: 'Regulated capitalist democracy', x: -3, y: 1, colors: ['#122a4a', '#7a1f2b', '#e8dcc0'], pattern: 'bars', description: 'Expanded the federal government\u2019s role in the economy with public works, financial regulation, and new social insurance programs, while remaining a competitive multi-party democracy.' },
  { name: 'Bonn Republic (West Germany)', flag: '🇩🇪', era: '1949–1990', govType: 'Social market democracy', x: -1, y: -2, colors: ['#1c1c1c', '#7a1f2b', '#c9a227'], pattern: 'quarter', description: 'Paired a competitive market economy with strong labor codetermination and a robust welfare state, rebuilding democratic institutions after the war under a decentralized federal constitution.' },
  { name: 'Modern Sweden', flag: '🇸🇪', era: '1945–present', govType: 'Universal welfare capitalism', x: -4, y: -3, colors: ['#0a5eb0', '#f0d048', '#e8dcc0'], pattern: 'orb', description: 'Combines a competitive, open market economy with high taxation funding universal healthcare, education, and family benefits, within a stable multi-party parliamentary system.' },
  { name: 'Modern Switzerland', flag: '🇨🇭', era: '1848–present', govType: 'Direct-democratic confederation', x: 3, y: -7, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'cross', description: 'A highly decentralized federation where citizens can directly propose and veto legislation by referendum, paired with a stable free-market economy and strict political neutrality.' },
  { name: 'Modern Singapore', flag: '🇸🇬', era: '1965–present', govType: 'Technocratic managed-market state', x: 4, y: 5, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'quarter', description: 'A city-state combining free-market economics and heavy foreign investment with strict social regulation and a dominant governing party that has held power continuously since independence.' },
  { name: 'Modern United States', flag: '🇺🇸', era: '1787–present', govType: 'Federal constitutional republic', x: 1, y: 0, colors: ['#122a4a', '#7a1f2b', '#e8dcc0'], pattern: 'bars', description: 'A federal republic with strong constitutional checks between branches and levels of government, and a mixed economy that leans more market-oriented than most peer democracies.' },
  { name: 'Modern China', flag: '🇨🇳', era: '1949–present', govType: 'One-party state capitalism', x: -2, y: 8, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'Combines market-driven growth and private enterprise with tight, centralized political control under a single party that permits no organized opposition.' },
  { name: 'Ancient Egypt (Old Kingdom)', era: 'c. 2686–2181 BC', govType: 'Theocratic pharaonic monarchy', x: -3, y: 8, colors: ['#c9a227', '#1c3a5e', '#1c1c1c'], pattern: 'eye', description: 'Ruled by a pharaoh regarded as a living god, who commanded vast state labor projects — including the pyramids — through a centralized granary economy and priestly bureaucracy.' },
  { name: 'Aztec Empire', era: '1428–1521', govType: 'Tribute-based militaristic theocracy', x: -5, y: 8, colors: ['#0e7c7b', '#c9a227', '#7a1f2b'], pattern: 'triangle', description: 'A triple alliance of city-states that extracted tribute and captives from conquered peoples to sustain both its economy and its religious rituals, under a highly militarized ruling class.' },
  { name: 'Song Dynasty China', era: '960–1279', govType: 'Commercial bureaucratic empire', x: 4, y: 2, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'quarter', description: 'Presided over an early commercial revolution — paper money, a vast merchant class, and technological innovation — governed by scholar-officials chosen through competitive examination.' },
  { name: 'Ottoman Empire (classical)', era: '1453–1600s', govType: 'Multi-ethnic imperial monarchy', x: 0, y: 6, colors: ['#123c2f', '#7a1f2b', '#c9a227'], pattern: 'orb', description: 'Governed a vast, religiously diverse empire through a millet system granting communities self-rule over their own religious affairs, under an otherwise centralized sultanate.' },
  { name: 'Kingdom of Prussia', era: '1701–1871', govType: 'Militarized absolutist monarchy', x: 0, y: 7, colors: ['#1c1c1c', '#e8dcc0', '#7a1f2b'], pattern: 'quarter', description: 'Built one of Europe\u2019s most disciplined and efficient state bureaucracies and armies, using both to punch well above its territorial weight in European politics.' },
  { name: 'Imperial Russia', flag: '🇷🇺', era: '1721–1917', govType: 'Autocratic monarchy', x: 1, y: 8, colors: ['#122a4a', '#c9a227', '#e8dcc0'], pattern: 'eye', description: 'Ruled by a hereditary tsar with near-total authority over a vast, largely agrarian empire, where serfdom persisted long after it had faded elsewhere in Europe.' },
  { name: 'French Third Republic', flag: '🇫🇷', era: '1870–1940', govType: 'Parliamentary democracy', x: -1, y: -1, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'France\u2019s longest-lived republic to that point, marked by a powerful but often unstable parliament, a growing welfare state, and deep ideological divides over religion and empire.' },
  { name: 'Modern France (Fifth Republic)', flag: '🇫🇷', era: '1958–present', govType: 'Semi-presidential republic', x: 0, y: 1, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'Combines a strong, directly elected president with a separate prime minister and parliament, and a mixed economy with a notably large public sector by European standards.' },
  { name: 'Modern Israel', flag: '🇮🇱', era: '1948–present', govType: 'Parliamentary democracy', x: 1, y: 1, colors: ['#1c3a8f', '#e8dcc0', '#c9a227'], pattern: 'cross', description: 'A parliamentary democracy with a highly fragmented multi-party system requiring coalition governments, and an economy that shifted from state-led socialism toward market liberalization over time.' },
  { name: 'Post-Apartheid South Africa', flag: '🇿🇦', era: '1994–present', govType: 'Constitutional democracy', x: -3, y: -3, colors: ['#2f6b3c', '#c9a227', '#1c1c1c'], pattern: 'eye', description: 'Replaced racial minority rule with a constitution built around reconciliation and extensive rights protections, while continuing to grapple with deep economic inequality inherited from apartheid.' },
  { name: 'Socialist Yugoslavia', era: '1945–1992', govType: 'Non-aligned socialist federation', x: -5, y: 3, colors: ['#122a4a', '#7a1f2b', '#e8dcc0'], pattern: 'spiral', description: 'Held together several distinct ethnic republics under a unique model of worker self-management rather than Soviet-style central planning, while steering an independent path in the Cold War.' },
  { name: 'Modern India', flag: '🇮🇳', era: '1947–present', govType: 'Federal parliamentary democracy', x: 1, y: 1, colors: ['#e8642c', '#f2e7cf', '#2f6b3c'], pattern: 'orb', description: 'The world\u2019s largest democracy, governing enormous linguistic and religious diversity through a federal parliamentary system atop a economy that shifted from state planning toward liberalization in the 1990s.' },
  { name: 'Reunified Germany', flag: '🇩🇪', era: '1990–present', govType: 'Federal parliamentary democracy', x: -1, y: -1, colors: ['#1c1c1c', '#7a1f2b', '#c9a227'], pattern: 'quarter', description: 'A federal republic built on a social market economy — competitive industry paired with strong labor codetermination and universal healthcare — within a stable multi-party coalition system.' },
  { name: 'Modern Japan', flag: '🇯🇵', era: '1947–present', govType: 'Constitutional monarchy', x: 3, y: 1, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'orb', description: 'A constitutional monarchy with a ceremonial emperor and an elected parliament, built around a highly coordinated market economy of close ties between government and major industry.' },
  { name: 'Modern Brazil', flag: '🇧🇷', era: '1988–present', govType: 'Federal presidential republic', x: -2, y: 1, colors: ['#2f6b3c', '#c9a227', '#122a4a'], pattern: 'bars', description: 'A federal presidential republic with a large, resource-driven economy and a strong tradition of social welfare spending, alongside significant regional and economic inequality.' },
  { name: 'Zulu Kingdom', era: '1816–1879', govType: 'Militarized centralized monarchy', x: -2, y: 9, colors: ['#7a1f2b', '#1c1c1c', '#c9a227'], pattern: 'triangle', description: 'Unified numerous smaller chiefdoms into a single centralized state under an innovative and highly disciplined military system organized around age-based regiments.' },
  { name: 'Kingdom of Hawaii', era: '1795–1893', govType: 'Constitutional monarchy', x: 1, y: 3, colors: ['#7a1f2b', '#c9a227', '#e8dcc0'], pattern: 'cross', description: 'Unified the Hawaiian islands under a single monarchy that later adopted a written constitution and parliament, before being overthrown in a coup backed by American business interests.' },
  { name: 'Cuba (Castro era)', flag: '🇨🇺', era: '1959–present', govType: 'Single-party socialist state', x: -9, y: 7, colors: ['#7a1f2b', '#1c1c1c', '#e8dcc0'], pattern: 'bars', description: 'Nationalized industry and land under a single party after its 1959 revolution, building universal healthcare and education systems while permitting no organized political opposition.' },
]

// ─────────────────────────────────────────────
// POLITICIANS
// A broad range of officeholders, monarchs, and revolutionary leaders
// across history and regions. Descriptions summarize their widely known
// public role in neutral terms; none of the text below is a quotation.
// ─────────────────────────────────────────────
export const politicians: Politician[] = [
  { name: 'Pericles', flag: '🇬🇷', title: 'Athenian statesman', era: 'c. 495–429 BC', x: -4, y: -3, colors: ['#f2e7cf', '#2a4f8f', '#c9a227'], pattern: 'eye', description: 'Led Athens through its democratic golden age, expanding public participation and funding ambitious civic building projects, while also presiding over Athenian imperial expansion abroad.' },
  { name: 'Cyrus the Great', flag: '🇮🇷', title: 'Founder of the Achaemenid Empire', era: 'c. 600–530 BC', x: 1, y: 4, colors: ['#5a2a7a', '#c9a227', '#e8dcc0'], pattern: 'orb', description: 'Built the ancient world\u2019s largest empire to date while allowing conquered peoples to retain their own religions, languages, and customs — an unusually tolerant approach for its era.' },
  { name: 'Ashoka the Great', flag: '🇮🇳', title: 'Mauryan emperor', era: '304–232 BC', x: -2, y: 3, colors: ['#e8642c', '#f2e7cf', '#2f6b3c'], pattern: 'orb', description: 'After a brutally costly conquest, renounced further military expansion and promoted Buddhist nonviolence, religious tolerance, and public welfare works across his empire.' },
  { name: 'Julius Caesar', flag: '🇮🇹', title: 'Roman general and dictator', era: '100–44 BC', x: -1, y: 7, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'triangle', description: 'A populist reformer who expanded citizenship and land grants for common soldiers and the poor, while concentrating political power in himself in ways that helped end the Roman Republic.' },
  { name: 'Augustus', flag: '🇮🇹', title: 'First Roman emperor', era: '63 BC – 14 AD', x: 1, y: 7, colors: ['#7a1f2b', '#e8dcc0', '#c9a227'], pattern: 'bars', description: 'Ended a century of civil war by consolidating power under himself while preserving republican forms and titles, founding an imperial system that endured for centuries.' },
  { name: 'Justinian I', title: 'Byzantine emperor', era: '482–565', x: 1, y: 8, colors: ['#3a1030', '#c9a227', '#e8dcc0'], pattern: 'cross', description: 'Codified Roman law into a lasting legal corpus and sought to reconquer the western empire, ruling as an absolute monarch closely tied to church authority.' },
  { name: 'Charlemagne', flag: '🇫🇷', title: 'Frankish emperor', era: '748–814', x: 2, y: 7, colors: ['#5a2a20', '#c9a227', '#e8dcc0'], pattern: 'cross', description: 'Unified much of Western Europe under a single Christian empire, promoting a revival of learning while ruling through direct personal and military authority.' },
  { name: 'Genghis Khan', flag: '🇲🇳', title: 'Founder of the Mongol Empire', era: 'c. 1162–1227', x: 0, y: 6, colors: ['#122a4a', '#e8dcc0', '#c9a227'], pattern: 'spiral', description: 'Unified the Mongol tribes and built the largest contiguous land empire in history through a meritocratic military hierarchy and overwhelming force.' },
  { name: 'Suleiman the Magnificent', flag: '🇹🇷', title: 'Ottoman sultan', era: '1494–1566', x: 1, y: 6, colors: ['#123c2f', '#c9a227', '#e8dcc0'], pattern: 'orb', description: 'Overhauled Ottoman law into a lasting legal code and presided over the empire\u2019s territorial and cultural height, ruling as an absolute monarch.' },
  { name: 'Elizabeth I', flag: '🇬🇧', title: 'Queen of England', era: '1533–1603', x: 3, y: 4, colors: ['#7a1f2b', '#c9a227', '#122a4a'], pattern: 'cross', description: 'Stabilized England after decades of religious conflict through pragmatic compromise, expanded overseas trade, and balanced royal authority against a growing Parliament.' },
  { name: 'Oliver Cromwell', flag: '🇬🇧', title: 'Lord Protector of England', era: '1599–1658', x: -2, y: 7, colors: ['#1c1c1c', '#7a1f2b', '#e8dcc0'], pattern: 'triangle', description: 'Led parliamentary forces to abolish the English monarchy, then ruled as a military strongman himself, blending republican rhetoric with authoritarian control.' },
  { name: 'Peter the Great', flag: '🇷🇺', title: 'Tsar of Russia', era: '1672–1725', x: 1, y: 8, colors: ['#122a4a', '#c9a227', '#7a1f2b'], pattern: 'eye', description: 'Forcibly modernized Russia\u2019s military, bureaucracy, and culture along Western lines, ruling as an absolute autocrat who tolerated no dissent from his reforms.' },
  { name: 'Frederick the Great', flag: '🇩🇪', title: 'King of Prussia', era: '1712–1786', x: 2, y: 6, colors: ['#1c1c1c', '#e8dcc0', '#c9a227'], pattern: 'quarter', description: 'An "enlightened absolutist" who patronized the arts and legal reform while personally holding unchecked authority and building Prussia into a major military power.' },
  { name: 'Catherine the Great', flag: '🇷🇺', title: 'Empress of Russia', era: '1729–1796', x: 2, y: 7, colors: ['#122a4a', '#c9a227', '#e8dcc0'], pattern: 'eye', description: 'Expanded Russian territory and patronized Enlightenment ideas and education, while ruling as an absolute monarch who tightened serfdom.' },
  { name: 'George Washington', flag: '🇺🇸', title: 'First U.S. president', era: '1732–1799', x: 2, y: 0, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'Voluntarily relinquished power after two terms, setting a precedent for peaceful transfer of power in the young republic he helped found.' },
  { name: 'Thomas Jefferson', flag: '🇺🇸', title: 'U.S. president', era: '1743–1826', x: 3, y: -4, colors: ['#122a4a', '#e8dcc0', '#c9a227'], pattern: 'bars', description: 'Championed an agrarian republic of small, independent landholders and strict limits on federal power, while personally holding enslaved people throughout his life.' },
  { name: 'Napoleon Bonaparte', flag: '🇫🇷', title: 'Emperor of the French', era: '1769–1821', x: 1, y: 7, colors: ['#122a4a', '#c9a227', '#7a1f2b'], pattern: 'eye', description: 'Rose from the French Revolution to crown himself emperor, exporting a unified legal code across Europe through both administrative reform and near-constant warfare.' },
  { name: 'Simón Bolívar', flag: '🇻🇪', title: 'South American independence leader', era: '1783–1830', x: -2, y: 2, colors: ['#c9a227', '#7a1f2b', '#2f6b3c'], pattern: 'triangle', description: 'Led independence movements across much of South America from Spanish rule, envisioning republican unity while at times assuming dictatorial powers to hold new states together.' },
  { name: 'Abraham Lincoln', flag: '🇺🇸', title: 'U.S. president', era: '1809–1865', x: -1, y: 1, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'Preserved the federal union through civil war and issued the Emancipation Proclamation, expanding federal and executive authority in the process.' },
  { name: 'Otto von Bismarck', flag: '🇩🇪', title: 'Chancellor of Germany', era: '1815–1898', x: -1, y: 5, colors: ['#1c1c1c', '#7a1f2b', '#e8dcc0'], pattern: 'quarter', description: 'Unified Germany through calculated diplomacy and war, then introduced Europe\u2019s first modern welfare programs partly to undercut rising socialist movements.' },
  { name: 'Mahatma Gandhi', flag: '🇮🇳', title: 'Indian independence leader', era: '1869–1948', x: -3, y: -6, colors: ['#f2e7cf', '#2f6b3c', '#c9a227'], pattern: 'eye', description: 'Led a mass nonviolent movement for Indian independence built on civil disobedience and self-reliant local economies, rejecting both colonial rule and centralized industrial power.' },
  { name: 'Vladimir Lenin', flag: '🇷🇺', title: 'Bolshevik revolutionary leader', era: '1870–1924', x: -9, y: 8, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'Led the Bolshevik seizure of power in 1917, abolishing private ownership of major industry and land and establishing a one-party state to direct the transition to communism.' },
  { name: 'Mustafa Kemal Atatürk', flag: '🇹🇷', title: 'Founder of modern Turkey', era: '1881–1938', x: -1, y: 5, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'quarter', description: 'Founded the Turkish Republic from the Ottoman Empire\u2019s remains, secularizing law and education and rapidly modernizing institutions through strong central authority.' },
  { name: 'Franklin D. Roosevelt', flag: '🇺🇸', title: 'U.S. president', era: '1882–1945', x: -3, y: 1, colors: ['#122a4a', '#7a1f2b', '#e8dcc0'], pattern: 'bars', description: 'Responded to the Great Depression with sweeping federal relief, recovery, and reform programs, permanently expanding the size and role of the U.S. federal government.' },
  { name: 'Winston Churchill', flag: '🇬🇧', title: 'British prime minister', era: '1874–1965', x: 2, y: 2, colors: ['#7a1f2b', '#122a4a', '#e8dcc0'], pattern: 'bars', description: 'Led Britain\u2019s wartime government against Nazi Germany, championing empire and traditional institutions while later overseeing the difficult early stages of imperial decline.' },
  { name: 'Mao Zedong', flag: '🇨🇳', title: 'Chairman of the Chinese Communist Party', era: '1893–1976', x: -9, y: 9, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'Led the Chinese Communist revolution and remade the economy around collective agriculture and state industry, concentrating political authority tightly around the party and himself.' },
  { name: 'Josip Broz Tito', title: 'President of Yugoslavia', era: '1892–1980', x: -5, y: 4, colors: ['#7a1f2b', '#c9a227', '#2f6b3c'], pattern: 'spiral', description: 'Ruled a multi-ethnic socialist federation through worker self-management rather than full Soviet-style central planning, and kept Yugoslavia independent of both Cold War blocs.' },
  { name: 'Nelson Mandela', flag: '🇿🇦', title: 'President of South Africa', era: '1918–2013', x: -2, y: -2, colors: ['#2f6b3c', '#f0d048', '#1c1c1c'], pattern: 'eye', description: 'Led the movement to end apartheid and, after 27 years of imprisonment, became president and pursued national reconciliation rather than retribution.' },
  { name: 'Margaret Thatcher', flag: '🇬🇧', title: 'British prime minister', era: '1925–2013', x: 6, y: 2, colors: ['#7a1f2b', '#122a4a', '#e8dcc0'], pattern: 'bars', description: 'Privatized state industries, curbed union power, and deregulated markets, reshaping British economic policy around free-market principles.' },
  { name: 'Ronald Reagan', flag: '🇺🇸', title: 'U.S. president', era: '1911–2004', x: 6, y: 1, colors: ['#122a4a', '#7a1f2b', '#e8dcc0'], pattern: 'bars', description: 'Cut taxes and regulation while significantly increasing defense spending, promoting a smaller domestic government paired with an assertive foreign policy.' },
  { name: 'Deng Xiaoping', flag: '🇨🇳', title: 'Paramount leader of China', era: '1904–1997', x: 3, y: 7, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'quarter', description: 'Opened China\u2019s economy to markets and foreign investment after Mao\u2019s death, delivering rapid growth while keeping political power concentrated in the Communist Party.' },
  { name: 'Mikhail Gorbachev', flag: '🇷🇺', title: 'Soviet leader', era: '1931–2022', x: -4, y: -1, colors: ['#7a1f2b', '#c9a227', '#e8dcc0'], pattern: 'spiral', description: 'Introduced political openness and market-oriented economic reforms that loosened one-party control, changes that ultimately contributed to the Soviet Union\u2019s dissolution.' },
  { name: 'Lee Kuan Yew', flag: '🇸🇬', title: "Singapore's founding prime minister", era: '1923–2015', x: 4, y: 6, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'quarter', description: 'Transformed Singapore into a wealthy global trade hub through free-market policy paired with strict social controls and limited political opposition.' },
  { name: 'Angela Merkel', flag: '🇩🇪', title: 'Chancellor of Germany, 2005–2021', era: '1954–', x: -1, y: -1, colors: ['#1c1c1c', '#7a1f2b', '#c9a227'], pattern: 'quarter', description: 'Governed through cautious, consensus-driven centrism for 16 years, steering Germany through the eurozone crisis and a major expansion of refugee admissions.' },
  { name: 'Bernie Sanders', flag: '🇺🇸', title: 'U.S. senator', era: '1941–', x: -7, y: -3, colors: ['#7a1f2b', '#122a4a', '#e8dcc0'], pattern: 'orb', description: 'A self-described democratic socialist who has campaigned for national health coverage, stronger labor protections, and reduced economic inequality through democratic institutions.' },
  { name: 'Javier Milei', flag: '🇦🇷', title: 'President of Argentina', era: '1970–', x: 8, y: -3, colors: ['#4a90d9', '#e8dcc0', '#122a4a'], pattern: 'bend', description: 'A self-described libertarian economist elected on a platform of drastic deregulation, spending cuts, and dollarization to fight chronic inflation.' },
  { name: 'Narendra Modi', flag: '🇮🇳', title: 'Prime Minister of India, since 2014', era: '1950–', x: 3, y: 3, colors: ['#e8642c', '#f2e7cf', '#2f6b3c'], pattern: 'orb', description: 'Pursues market-oriented economic reform alongside Hindu nationalist cultural policy, governing with a strong parliamentary majority and centralized personal authority.' },
  { name: 'Xi Jinping', flag: '🇨🇳', title: 'General Secretary of the CCP, since 2012', era: '1953–', x: -3, y: 9, colors: ['#7a1f2b', '#c9a227', '#1c1c1c'], pattern: 'bars', description: 'Has tightened one-party control over China\u2019s economy, media, and civil society more than any leader since Mao, while continuing state-guided market growth.' },
  { name: 'Hammurabi', flag: '🇮🇶', title: 'King of Babylon', era: 'c. 1810–1750 BC', x: 1, y: 7, colors: ['#c9a227', '#1c1c1c', '#7a1f2b'], pattern: 'bars', description: 'Issued one of the earliest known written legal codes, publicly inscribed to standardize justice across his kingdom, while ruling as an absolute monarch.' },
  { name: 'Ramesses II', flag: '🇪🇬', title: 'Pharaoh of Egypt', era: 'c. 1303–1213 BC', x: 0, y: 8, colors: ['#c9a227', '#1c3a5e', '#7a1f2b'], pattern: 'eye', description: 'Ruled as a god-king for over 60 years, commanding massive monument-building projects and concluding one of history\u2019s earliest surviving peace treaties after a major war.' },
  { name: 'Hatshepsut', flag: '🇪🇬', title: 'Pharaoh of Egypt', era: 'c. 1507–1458 BC', x: 0, y: 6, colors: ['#c9a227', '#f2e7cf', '#1c3a5e'], pattern: 'eye', description: 'One of the few women to rule Egypt as pharaoh in her own right, presiding over an era of prosperous trade expeditions and ambitious monument building.' },
  { name: 'Alexander the Great', flag: '🇬🇷', title: 'King of Macedon', era: '356–323 BC', x: 0, y: 7, colors: ['#122a4a', '#c9a227', '#7a1f2b'], pattern: 'triangle', description: 'Conquered an empire stretching from Greece to India in barely a decade, spreading Greek culture widely while ruling through absolute personal authority.' },
  { name: 'Marcus Aurelius', flag: '🇮🇹', title: 'Roman emperor', era: '121–180', x: 1, y: 5, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'quarter', description: 'A Stoic philosopher who governed the empire during years of war and plague, remembered for tempering absolute imperial power with a strong personal sense of duty and restraint.' },
  { name: 'Saladin', flag: '🇪🇬', title: 'Sultan of Egypt and Syria', era: 'c. 1137–1193', x: 0, y: 5, colors: ['#123c2f', '#c9a227', '#e8dcc0'], pattern: 'orb', description: 'Unified Egypt and Syria and recaptured Jerusalem, earning a reputation even among his adversaries for relatively merciful treatment of defeated populations.' },
  { name: 'Louis XIV', flag: '🇫🇷', title: 'King of France', era: '1638–1715', x: 1, y: 9, colors: ['#122a4a', '#c9a227', '#e8dcc0'], pattern: 'eye', description: 'The archetypal absolute monarch, who centralized power at Versailles, reduced the nobility to court dependents, and famously equated his own person with the state.' },
  { name: 'Queen Victoria', flag: '🇬🇧', title: 'Queen of the United Kingdom', era: '1819–1901', x: 2, y: 3, colors: ['#7a1f2b', '#1c1c1c', '#c9a227'], pattern: 'cross', description: 'Reigned as a largely ceremonial constitutional monarch through Britain\u2019s industrial and imperial peak, as real governing power shifted decisively to Parliament.' },
  { name: 'Toussaint Louverture', flag: '🇭🇹', title: 'Leader of the Haitian Revolution', era: 'c. 1743–1803', x: -3, y: 3, colors: ['#122a4a', '#c9a227', '#7a1f2b'], pattern: 'triangle', description: 'Led the only successful large-scale slave revolt in history, abolishing slavery in Haiti and governing the colony before its final push to independence.' },
  { name: 'Benito Juárez', flag: '🇲🇽', title: 'President of Mexico', era: '1806–1872', x: -2, y: -1, colors: ['#2f6b3c', '#f2e7cf', '#7a1f2b'], pattern: 'bars', description: 'Led liberal reforms separating church and state and expanding secular education, defending Mexican republicanism against foreign-imposed monarchy.' },
  { name: 'Charles de Gaulle', flag: '🇫🇷', title: 'President of France', era: '1890–1970', x: 1, y: 3, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'Founded France\u2019s Fifth Republic with a strengthened presidency, pursuing an independent foreign policy while presiding over continued postwar economic modernization.' },
  { name: 'Woodrow Wilson', flag: '🇺🇸', title: 'U.S. president', era: '1856–1924', x: -1, y: 1, colors: ['#122a4a', '#e8dcc0', '#7a1f2b'], pattern: 'bars', description: 'Expanded federal regulatory power and promoted international cooperation through the League of Nations, while also overseeing the resegregation of the federal workforce.' },
  { name: 'Theodore Roosevelt', flag: '🇺🇸', title: 'U.S. president', era: '1858–1919', x: 0, y: 2, colors: ['#122a4a', '#2f6b3c', '#e8dcc0'], pattern: 'bars', description: 'Broke up major monopolies, championed national conservation of public lands, and expanded American influence abroad through an assertive, personally-driven executive style.' },
  { name: 'Golda Meir', flag: '🇮🇱', title: 'Prime Minister of Israel', era: '1898–1978', x: -2, y: 1, colors: ['#1c3a8f', '#e8dcc0', '#c9a227'], pattern: 'cross', description: 'Led Israel through the 1973 war and helped build its early welfare institutions, governing within a fragile multi-party coalition system.' },
  { name: 'Indira Gandhi', flag: '🇮🇳', title: 'Prime Minister of India', era: '1917–1984', x: -3, y: 3, colors: ['#e8642c', '#f2e7cf', '#2f6b3c'], pattern: 'orb', description: 'Nationalized banks and pursued state-led development, and at one point suspended civil liberties and ruled by emergency decree before restoring democratic elections.' },
  { name: 'Willy Brandt', flag: '🇩🇪', title: 'Chancellor of Germany', era: '1913–1992', x: -3, y: -2, colors: ['#1c1c1c', '#7a1f2b', '#c9a227'], pattern: 'quarter', description: 'Pursued reconciliation with Eastern Europe through "Ostpolitik" and expanded West Germany\u2019s welfare state, governing through consensus-based coalition politics.' },
  { name: 'Kwame Nkrumah', flag: '🇬🇭', title: "Ghana's founding president", era: '1909–1972', x: -5, y: 3, colors: ['#7a1f2b', '#c9a227', '#2f6b3c'], pattern: 'triangle', description: 'Led Ghana to independence and championed pan-African unity and state-led industrialization, before consolidating power into a one-party state.' },
  { name: 'Haile Selassie', flag: '🇪🇹', title: 'Emperor of Ethiopia', era: '1892–1975', x: 0, y: 6, colors: ['#2f6b3c', '#f0d048', '#7a1f2b'], pattern: 'eye', description: 'Modernized Ethiopia\u2019s institutions and gave a landmark speech to the League of Nations against foreign invasion, while ruling as an absolute monarch until deposed.' },
  { name: 'Fidel Castro', flag: '🇨🇺', title: 'Leader of Cuba', era: '1926–2016', x: -9, y: 8, colors: ['#7a1f2b', '#1c1c1c', '#e8dcc0'], pattern: 'bars', description: 'Led a guerrilla revolution that nationalized industry and land, building universal healthcare and education under a one-party state that tolerated no organized opposition.' },
  { name: 'Nikita Khrushchev', flag: '🇷🇺', title: 'Soviet leader', era: '1894–1971', x: -7, y: 5, colors: ['#7a1f2b', '#c9a227', '#e8dcc0'], pattern: 'spiral', description: 'Denounced Stalin\u2019s worst abuses and eased some political repression, while remaining committed to one-party rule and central economic planning.' },
  { name: 'Recep Tayyip Erdoğan', flag: '🇹🇷', title: 'President of Turkey', era: '1954–', x: -1, y: 7, colors: ['#7a1f2b', '#e8dcc0', '#1c1c1c'], pattern: 'quarter', description: 'Has overseen a shift from parliamentary to presidential government with steadily expanding executive power, combining market-friendly growth with religiously conservative social policy.' },
  { name: 'Luiz Inácio Lula da Silva', flag: '🇧🇷', title: 'President of Brazil', era: '1945–', x: -4, y: -1, colors: ['#2f6b3c', '#c9a227', '#122a4a'], pattern: 'bars', description: 'A former union leader who expanded anti-poverty and social welfare programs as president, governing within Brazil\u2019s competitive multi-party democracy.' },
]

// ─────────────────────────────────────────────
// QUESTIONS
// Same -2..2 response scale and econ/auth axes as the Political Compass,
// framed around governance, history, and the exercise of power.
// ─────────────────────────────────────────────
export const politicianNationQuestions: Question[] = [
  { id: 'pn1', text: 'A strong central authority is often necessary to hold a diverse population together.', axes: { auth: 1.5 } },
  { id: 'pn2', text: 'The best leaders are the ones willing to act decisively without waiting for consensus.', axes: { auth: 1.5 } },
  { id: 'pn3', text: 'Major industries and infrastructure are best run by the state rather than private owners.', axes: { econ: -1.5 } },
  { id: 'pn4', text: 'A nation should prioritize expanding its trade and influence abroad, even at some risk.', axes: { auth: 1 } },
  { id: 'pn5', text: 'Ordinary citizens should have the power to directly veto laws they disagree with.', axes: { auth: -1.5 } },
  { id: 'pn6', text: 'Rapid, top-down modernization is often worth the social disruption it causes.', axes: { auth: 1.5, econ: 0.5 } },
  { id: 'pn7', text: 'Private property and free exchange should rarely, if ever, be overridden by the state.', axes: { econ: 1.5 } },
  { id: 'pn8', text: 'Tradition and established institutions deserve more weight than bold new reforms.', axes: { auth: 1 } },
  { id: 'pn9', text: 'A country\'s wealth is best built through trade and commerce rather than conquest.', axes: { econ: 1, auth: -1 } },
  { id: 'pn10', text: 'Political power should be widely distributed rather than concentrated in a single office.', axes: { auth: -2 } },
  { id: 'pn11', text: 'Redistributing wealth to reduce inequality is one of government\'s most important jobs.', axes: { econ: -1.5 } },
  { id: 'pn12', text: 'Military strength is the ultimate guarantee of a nation\'s independence.', axes: { auth: 1 } },
  { id: 'pn13', text: 'Reconciliation with former adversaries matters more than punishing them for past wrongs.', axes: { auth: -1.5 } },
  { id: 'pn14', text: 'A leader should be willing to bend or suspend existing rules to achieve a greater good.', axes: { auth: 2 } },
  { id: 'pn15', text: 'Nonviolent resistance is more effective, and more legitimate, than armed rebellion.', axes: { auth: -1.5 } },
  { id: 'pn16', text: 'Deregulating markets tends to produce more prosperity than managing them closely.', axes: { econ: 1.5 } },
  { id: 'pn17', text: 'A well-run state should plan the economy rather than leave outcomes to the market.', axes: { econ: -2 } },
  { id: 'pn18', text: 'Tolerating a wide range of religions and customs strengthens a large, diverse state.', axes: { auth: -1 } },
  { id: 'pn19', text: 'Codifying laws into one clear, unified system is a mark of good governance.', axes: { auth: 0.5 } },
  { id: 'pn20', text: 'Legitimate authority ultimately rests on the consent of the governed, not force.', axes: { auth: -2 } },
]
